### ISSUE TITLE
unit test problem

### ISSUE THREAD

**Issue by lijinpvlm** [jeff1evesque/machine-learning#3107] opened 2017-11-10 13:58 UTC
vagrant@trusty64:/vagrant/test$ ./unit-tests not working in unix 
what is the comand to do unit test

**Comment by jeff1evesque** [comment] 2017-11-10 22:49
You need to build the vagrant environment via `vagrant up`, then ssh into the corresponding build, via `vagrant ssh`. This will allow you to run the corresponding unit tests:

```bash
sudo su
cd /vagrant
./unit-tests
```

**Comment by jeff1evesque** [comment] 2017-11-11 03:25
Also, please post corresponding error trace, either from `vagrant up`, or the corresponding error(s) when running `./unit-tests`. I'm going to close this issue, until further information is provided.

**Closed by jeff1evesque** 2017-11-11 03:25 UTC
Labels: awaiting response, question

**Comment by lijinpvlm** [comment] 2017-11-11 05:26
I have done vagrant up and corresponding things and the vm is created .The next thing is to do unit test right. i can't run unit test in unix environment.The following command is not working and displaying command not found.

**Comment by lijinpvlm** [comment] 2017-11-11 05:26
I have done vagrant up and corresponding things and the vm is created .The next thing is to do unit test right. i can't run unit test in unix environment.The following command is not working and displaying command not found.
vagrant@trusty64:/vagrant/test$ ./unit-tests

**Comment by jeff1evesque** [comment] 2017-11-12 10:53
Looks like you're not letting the test run long enough:

```bash
root@trusty64:/vagrant/test# ./unit-tests
usermod: group 'docker' does not exist
sudo: docker: command not found
sudo: docker: command not found
sudo: docker: command not found
sudo: docker: command not found
sudo: docker: command not found
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  libcurl3 python3-software-properties
The following packages will be upgraded:
  apt-transport-https ca-certificates curl libcurl3
  python3-software-properties software-properties-common
6 upgraded, 0 newly installed, 0 to remove and 123 not upgraded.
Need to get 516 kB of archives.
After this operation, 41.0 kB disk space will be freed.
Get:1 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main curl amd64 7.35.0-1ubuntu2.12 [123 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main libcurl3 amd64 7.35.0-1ubuntu2.12 [173 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main apt-transport-https amd64 1.0.1ubuntu2.17 [25.0 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main ca-certificates all 20170717~14.04.1 [167 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main software-properties-common all 0.92.37.8 [9,384 B]
Get:6 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main python3-software-properties all 0.92.37.8 [19.2 kB]
Fetched 516 kB in 0s (1,640 kB/s)
Preconfiguring packages ...
[...OMITTED-CODE...]
```

**Comment by jeff1evesque** [comment] 2017-11-12 11:11
The above `[...OMITTED-CODE...]` should end as follows:

```bash
vagrant@trusty64:/vagrant/test$ ./unit-tests
...
============================= test session starts ==============================
platform linux2 -- Python 2.7.6, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: /var/machine-learning/test/live_server, inifile: pytest.ini
plugins: flask-0.10.0, cov-2.4.0
collected 57 items
test/live_server/1_authentication/pytest_1_crypto.py .
test/live_server/1_authentication/pytest_2_account_registration.py .
test/live_server/1_authentication/pytest_3_validate_password.py .
test/live_server/1_authentication/pytest_4_user_login.py .
test/live_server/1_authentication/pytest_5_user_logout.py .
test/live_server/1_authentication/pytest_6_user_session.py .
test/live_server/2_database/pytest_svm_dbmax.py ..........
test/live_server/2_database/pytest_svr_dbmax.py ..........
test/live_server/3_programmatic_interface/dataset_url/pytest_bagc_dataset_url.py ....
test/live_server/3_programmatic_interface/dataset_url/pytest_svm_dataset_url.py ....
test/live_server/3_programmatic_interface/dataset_url/pytest_svr_dataset_url.py ....
test/live_server/3_programmatic_interface/file_upload/pytest_bagc_file_upload.py ....
test/live_server/3_programmatic_interface/file_upload/pytest_svm_file_upload.py ....
test/live_server/3_programmatic_interface/file_upload/pytest_svr_file_upload.py ....
test/live_server/3_programmatic_interface/results/pytest_1_svm_prediction.py ...
test/live_server/3_programmatic_interface/results/pytest_2_svr_prediction.py ...
test/live_server/3_programmatic_interface/results/pytest_3_all_prediction_titles.py .

---------- coverage: platform linux2, python 2.7.6-final-0 -----------
Name                                                                                  Stmts   Miss  Cover
---------------------------------------------------------------------------------------------------------
__init__.py                                                                               0      0   100%
app.py                                                                                   12     12     0%
brain/__init__.py                                                                         0      0   100%
brain/cache/__init__.py                                                                   0      0   100%
brain/cache/hset.py                                                                      22     14    36%
brain/cache/model.py                                                                     34     24    29%
brain/cache/query.py                                                                     87     77    11%
brain/cache/session.py                                                                   51     32    37%
brain/cache/settings.py                                                                  14     10    29%
brain/converter/__init__.py                                                               0      0   100%
brain/converter/crypto.py                                                                45      6    87%
brain/converter/format/__init__.py                                                        0      0   100%
brain/converter/format/csv2dict.py                                                       21     21     0%
brain/converter/format/xml2dict.py                                                       19     19     0%
brain/converter/md5.py                                                                    9      9     0%
brain/converter/model.py                                                                 12      7    42%
brain/converter/operation.py                                                             45     45     0%
brain/converter/settings.py                                                              50     50     0%
brain/database/__init__.py                                                                0      0   100%
brain/database/account.py                                                                53     15    72%
brain/database/dataset.py                                                                16      6    63%
brain/database/entity.py                                                                 60     22    63%
brain/database/model_type.py                                                             17      7    59%
brain/database/prediction.py                                                             89     19    79%
brain/database/query.py                                                                 125     59    53%
brain/database/session.py                                                                30     20    33%
brain/database/settings.py                                                               46     24    48%
brain/load_data.py                                                                       83     37    55%
brain/schema/__init__.py                                                                  0      0   100%
brain/schema/dataset.py                                                                   7      3    57%
brain/schema/session.py                                                                  13      5    62%
brain/session/__init__.py                                                                 0      0   100%
brain/session/base.py                                                                    25     15    40%
brain/session/base_data.py                                                               61     25    59%
brain/session/data/__init__.py                                                            0      0   100%
brain/session/data/dataset.py                                                            70     49    30%
brain/session/data_append.py                                                             29     12    59%
brain/session/data_new.py                                                                27     10    63%
brain/session/model/__init__.py                                                           0      0   100%
brain/session/model/adabooster.py                                                        50     50     0%
brain/session/model/bagger.py                                                            59     18    69%
brain/session/model/sv.py                                                                44      8    82%
brain/session/model_generate.py                                                          26     10    62%
brain/session/model_predict.py                                                           20      9    55%
brain/session/predict/__init__.py                                                         0      0   100%
brain/session/predict/adaboost.py                                                        18     18     0%
brain/session/predict/bag.py                                                             27      8    70%
brain/session/predict/sv.py                                                              22      5    77%
brain/validator/__init__.py                                                               0      0   100%
brain/validator/dataset.py                                                               16     16     0%
brain/validator/email.py                                                                  7      3    57%
brain/validator/password.py                                                              43      4    91%
brain/validator/settings.py                                                              41     18    56%
factory.py                                                                               55     16    71%
interface/__init__.py                                                                     0      0   100%
interface/views.py                                                                      248    143    42%
log/__init__.py                                                                           0      0   100%
log/logger.py                                                                            84     84     0%
puppet/__init__.py                                                                        0      0   100%
puppet/environment/__init__.py                                                            0      0   100%
puppet/environment/docker/__init__.py                                                     0      0   100%
puppet/environment/docker/modules/__init__.py                                             0      0   100%
puppet/environment/docker/modules/mariadb/__init__.py                                     0      0   100%
puppet/environment/docker/modules/mariadb/scripts/__init__.py                             0      0   100%
puppet/environment/docker/modules/mariadb/scripts/setup_tables.py                        40     40     0%
puppet/environment/vagrant/__init__.py                                                    0      0   100%
puppet/environment/vagrant/modules/__init__.py                                            0      0   100%
puppet/environment/vagrant/modules/mariadb/__init__.py                                    0      0   100%
puppet/environment/vagrant/modules/mariadb/scripts/__init__.py                            0      0   100%
puppet/environment/vagrant/modules/mariadb/scripts/setup_tables.py                       40     40     0%
test/live_server/1_authentication/pytest_1_crypto.py                                     15      2    87%
test/live_server/1_authentication/pytest_2_account_registration.py                       21      3    86%
test/live_server/1_authentication/pytest_3_validate_password.py                          16      2    88%
test/live_server/1_authentication/pytest_4_user_login.py                                 19      3    84%
test/live_server/1_authentication/pytest_5_user_logout.py                                12      0   100%
test/live_server/1_authentication/pytest_6_user_session.py                               16      1    94%
test/live_server/2_database/pytest_svm_dbmax.py                                         102      0   100%
test/live_server/2_database/pytest_svr_dbmax.py                                         103      0   100%
test/live_server/3_programmatic_interface/dataset_url/pytest_bagc_dataset_url.py         37      0   100%
test/live_server/3_programmatic_interface/dataset_url/pytest_svm_dataset_url.py          52      0   100%
test/live_server/3_programmatic_interface/dataset_url/pytest_svr_dataset_url.py          42      0   100%
test/live_server/3_programmatic_interface/file_upload/pytest_bagc_file_upload.py         36      0   100%
test/live_server/3_programmatic_interface/file_upload/pytest_svm_file_upload.py          52      0   100%
test/live_server/3_programmatic_interface/file_upload/pytest_svr_file_upload.py          42      0   100%
test/live_server/3_programmatic_interface/results/pytest_1_svm_prediction.py             64     17    73%
test/live_server/3_programmatic_interface/results/pytest_2_svr_prediction.py             62     17    73%
test/live_server/3_programmatic_interface/results/pytest_3_all_prediction_titles.py      33      7    79%
test/live_server/conftest.py                                                             12      2    83%
---------------------------------------------------------------------------------------------------------
TOTAL                                                                                  2748   1198    56%
=============================== warnings summary ===============================
3_programmatic_interface/results/pytest_1_svm_prediction.py::test_save_prediction
  /var/machine-learning/brain/database/query.py:281: Warning: Data truncated for column 'probability' at row 1
    self.cursor.execute(statement, sql_args)
  /var/machine-learning/brain/database/query.py:281: Warning: Data truncated for column 'decision_function' at row 1
    self.cursor.execute(statement, sql_args)

3_programmatic_interface/results/pytest_2_svr_prediction.py::test_save_prediction
  /var/machine-learning/brain/database/query.py:281: Warning: Data truncated for column 'r2' at row 1
    self.cursor.execute(statement, sql_args)

-- Docs: http://doc.pytest.org/en/latest/warnings.html
=================== 57 passed, 3 warnings in 120.34 seconds ====================
```

If you're having problems with that, it's probably due to your network, proxy, or you have modified the code somehow. I won't be able to assist you otherwise, since I personally created a new build, and ran a full unit test, and was not able to reproduce your uninformative question.

**Comment by jeff1evesque** [comment] 2017-11-12 11:13
Keep in mind, if you figure out your network, proxy, internet problems (the things I will not be able to debug), your above run will be slightly different, since the above is predicated on the `milestone-0.9` branch, which includes other features I'm working on, which entails additional unit tests, not currently merged to the projects `master` branch.
