### ISSUE TITLE
Include 'ESLint' tool into the project

### ISSUE THREAD

**Issue by Vitao18** [jeff1evesque/machine-learning#3053] opened 2017-10-14 17:33 UTC
Add [ESLint with Airbnb](https://www.npmjs.com/package/eslint-config-airbnb) configuration into the project. 
It'll ensure that the code have a guideline to be followed and we'll be able to prevent bugs upfront.

**Comment by jeff1evesque** [comment] 2017-10-14 17:44
Do you have an example of how to run eslint, can it be added as a flag to babelify, or browserify command?

**Comment by jeff1evesque** [comment] 2017-10-14 17:47
This repository does have an [`eslint.json`](https://github.com/jeff1evesque/machine-learning/blob/582a03da2ccc1dcde2850be3574bbc25ec75e5a6/test/lint/eslint.json). I wouldn't mind changing it for valid reason(s).  Is it possible to use this configuration to manually lint the corresponding [`src/jsx`](https://github.com/jeff1evesque/machine-learning/tree/582a03da2ccc1dcde2850be3574bbc25ec75e5a6/src/jsx) directory?

**Comment by Vitao18** [comment] 2017-10-14 18:06
"This repository does have an eslint.json. I wouldn't mind changing it for valid reason(s). Is it possible to use this configuration to manually lint the corresponding src/jsx directory?"
I'll try to do it!
But keep in mind that this configuation will ignore node_modules and non-js/jsx files

**Comment by Vitao18** [comment] 2017-10-14 18:07
"Do you have an example of how to run eslint, can it be added as a flag to babelify, or browserify?"
You only to npm install again and set your editor to have the eslint plugin. As you develop you will see the error displayed on the go.
Also, you can run './node_modules/.bin/eslint yourfile.js' and the yourfile.js will be open with the errors in your project

**Comment by jeff1evesque** [comment] 2017-10-14 18:22
>Also, you can run './node_modules/.bin/eslint yourfile.js' and the yourfile.js will be open with the errors in your project

So, it helps highlight the syntax errors in the editor, and can potentially fix them too?

**Comment by Vitao18** [comment] 2017-10-14 18:30
> So, it helps highlight the syntax errors in the editor, and can potentially fix them too?

Yes! Not only syntax errors but anything that doesn't follow the lint configuration(airbnb in this case). Also, it'll highlight any bad patterns in the code (eg. as setting state in ComponentDidMount)

**Comment by jeff1evesque** [comment] 2017-10-14 18:40
Ah, ok. To me it's trivial, whether airbnb, facebook, or some other configuration.  Though, to be consistent, we'll probably need to adjust the [`eslint.json`](https://github.com/jeff1evesque/machine-learning/blob/582a03da2ccc1dcde2850be3574bbc25ec75e5a6/test/lint/eslint.json) (what travis ci uses), to be the same set of rules. If you want to commit that change in this issue, or open another one, that's up to you.  Also, would you mind, adding a `development` directory in the [docs](https://github.com/jeff1evesque/machine-learning/tree/master/doc), and create an rst file, with minimal language explaining how to setup the linter, what editors, and corresponding plugins are acceptable to use these linters?

**Comment by Vitao18** [comment] 2017-10-14 18:44
> Ah, ok. To me it's trivial, whether airbnb, facebook, or some other configuration. Though, to be consistent, we'll probably need to adjust the eslint.json (what travis ci uses), to be the same set of rules. If you want to commit that change in this issue, or open another one, that's up to you. Also, would you mind, adding a development directory in the docs, and create an rst file, with minimal language explaining how to setup the linter, what editors, and corresponding plugins are acceptable to use these linters?

Sure! I'll do those changes after I solve #3047, ok?

**Comment by jeff1evesque** [comment] 2017-10-14 18:47
Sounds good.

**Comment by jeff1evesque** [comment] 2018-01-07 00:32
This issue is `invalid`, and a duplicate of #2426, since `eslint` is already installed as part of our puppet build`.  Additionally, when the changes from #2426 completes, it should suffice, until further requirements are made.

**Closed by jeff1evesque** 2018-01-07 00:32 UTC
Labels: frontend

**Comment by jeff1evesque** [comment] 2018-01-07 00:33
This issue is `invalid`, and a `duplicate` of #2426, since `eslint` is already installed via our puppet build`.  Additionally, when the changes from #2426 completes, it should suffice, until further requirements are made.
