### ISSUE TITLE
Can't do unit test

### ISSUE THREAD

**Issue by lijinpvlm** [jeff1evesque/machine-learning#3108] opened 2017-11-11 05:58 UTC
![image](https://user-images.githubusercontent.com/33484961/32686808-5463312a-c6d3-11e7-96f3-c07c1baa37cf.png)

I have done vagrant up and corresponding things and the vm is created .The next thing is to do unit test right. i can't run unit test in unix environment.The following command is not working and displaying command not found.
vagrant@trusty64:/vagrant/test$ ./unit-tests

**Comment by jeff1evesque** [comment] 2017-11-11 06:14
Show me the following:

You need to build the vagrant environment via `vagrant up`, then ssh into the corresponding build, via `vagrant ssh`. This will allow you to run the corresponding unit tests:

```bash
sudo su
cd /vagrant/test
ls -l
```

**Comment by jeff1evesque** [comment] 2017-11-11 06:17
This is a duplicate of your previous issue #3107.

**Closed by jeff1evesque** 2017-11-11 06:17 UTC
Labels: duplicate
