### ISSUE TITLE
The SSH command responded with a non-zero exit status

### ISSUE THREAD

**Issue by chickuvlm** [jeff1evesque/machine-learning#3111] opened 2017-11-14 09:23 UTC
![screen shot 2017-11-14 at 2 37 22 pm](https://user-images.githubusercontent.com/33593593/32772306-719042d6-c94b-11e7-87e3-22ab9e1f3edc.png)
how to solve this

**Comment by jeff1evesque** [comment] 2017-11-14 10:30
This issue is a duplicate of #3107, and cannot be reproduced. It is likely you have modified the source cod of the project, before the build.

**Comment by chickuvlm** [comment] 2017-11-14 10:39
no i have't modified the code.After the generation of ssh keys, the code is clone to my mac pc(which is having 15gb of available memory).Then i did vagrant up and finally vagrant ssh.Then i did unit-tests.what is wrong with this.
Please help me

**Comment by jeff1evesque** [comment] 2017-11-14 10:46
I'm not sure, I am unable to reproduce your errors. And your screenshots are not really helpful, since simply saying something doesn't work, could have more than a thousand different interpretations.

**Comment by jeff1evesque** [comment] 2017-11-14 11:13
Closing this issue, since it's a duplicate to #3107. Please use your original issue.

**Closed by jeff1evesque** 2017-11-14 11:13 UTC
Labels: duplicate, invalid, question

**Comment by jeff1evesque** [comment] 2017-11-14 13:36
Your screenshot in this issue seems to indicate there was problems related to babel, browserify, and babelify packages. I suspect it's some kind of network problem, perhaps the package mirror repositories (like `apt-get`), that you are using, are not adequate. But, the unit tests seem fine, since travis ci ran last night without a problem:

- https://travis-ci.org/jeff1evesque/machine-learning/builds/301768458

Please, do not open more issues on the same problem.  Use your original issue via #3107.
